version: "3.1"

services:

  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: teste_postgre
      TZ: 'GMT-3'
      PGTZ: 'GMT-3'
    ports:
      - 5432:5432