"""first revision

Revision ID: 91efd44f994d
Revises: 
Create Date: 2023-09-27 13:40:46.744450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91efd44f994d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_status', sa.Boolean(), nullable=False),
    sa.Column('sheet_name', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('main_column', sa.String(), nullable=False),
    sa.Column('auxiliary_column', sa.String(), nullable=True),
    sa.Column('reference_values', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_tasks_task_status'), 'tasks', ['task_status'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tasks_runtime',
    sa.Column('tasks_runtime_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('runtime', sa.Time(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tasks_runtime_id')
    )
    op.create_index(op.f('ix_tasks_runtime_runtime'), 'tasks_runtime', ['runtime'], unique=False)
    op.create_table('tasksweekdays',
    sa.Column('task_weekday_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sunday', sa.Boolean(), nullable=True),
    sa.Column('monday', sa.Boolean(), nullable=True),
    sa.Column('tuesday', sa.Boolean(), nullable=True),
    sa.Column('wednesday', sa.Boolean(), nullable=True),
    sa.Column('thursday', sa.Boolean(), nullable=True),
    sa.Column('friday', sa.Boolean(), nullable=True),
    sa.Column('saturday', sa.Boolean(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_weekday_id')
    )
    op.create_table('users_tasks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'task_id')
    )
    op.create_table('achieved_tasks',
    sa.Column('achieved_tasks_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('tasks_runtime_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tasks_runtime_id'], ['tasks_runtime.tasks_runtime_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('achieved_tasks_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('achieved_tasks')
    op.drop_table('users_tasks')
    op.drop_table('tasksweekdays')
    op.drop_index(op.f('ix_tasks_runtime_runtime'), table_name='tasks_runtime')
    op.drop_table('tasks_runtime')
    op.drop_table('users')
    op.drop_index(op.f('ix_tasks_task_status'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
